// Tests for assertWeekdayClaims in src/dateFacts.js (report bug 3, validator V3).
//
// Day 5 of the 2026-07-28 build was Monday Oct 5. It booked La Rapiere, which
// closes Mondays, and carried the verify note "this is a Tuesday, confirm
// open". The false premise is what talked the expert review past the closure.
//
// CLAUDE.md: "Day-of-week … COMPUTED IN CODE, never generated by the model."
// So a wrong claim is rewritten, not merely annotated. The rewrite is
// deliberately narrow — see the last block, which is the important one: a
// venue's real closure data must never be edited.

import { assertWeekdayClaims, enforceDayLabelDates, enforceMetaDateRange } from "../src/dateFacts.js";

let passed = 0, failed = 0;
function assert(name, cond, detail = "") {
  if (cond) { passed++; console.log("  ✓", name); }
  else { failed++; console.log("  ✗", name, detail); }
}

// 2026-10-01 is a Thursday, so Day 5 is Monday 2026-10-05.
const START = "2026-10-01";

console.log("=== the shipped failure: \"this is a Tuesday\" on a Monday ===");
{
  const plan = {
    days: [
      { day: 1, city: "Bayeux", items: [] },
      { day: 2, city: "Bayeux", items: [] },
      { day: 3, city: "Bayeux", items: [] },
      { day: 4, city: "Bayeux", items: [] },
      {
        day: 5,
        city: "Bayeux",
        items: [{
          type: "Dinner",
          text: "Dinner at La Rapiere",
          restaurant: { name: "La Rapiere" },
          verify_status: "Closed Mondays per Places — but this is a Tuesday, confirm open.",
        }],
      },
    ],
  };
  const { plan: fixed, flags, corrections } = assertWeekdayClaims(plan, START);
  const note = fixed.days[4].items[0].verify_status;

  assert("the self-referential claim is corrected", /this is a Monday/.test(note), note);
  assert("the venue's real closure data is untouched", /Closed Mondays per Places/.test(note), note);
  assert("one flag raised", flags.length === 1, JSON.stringify(flags));
  assert("code is WEEKDAY_CLAIM_MISMATCH", flags[0]?.code === "WEEKDAY_CLAIM_MISMATCH");
  assert("severity is warn — the text is already fixed", flags[0]?.severity === "warn");
  assert("dayIdx is 0-based", flags[0]?.dayIdx === 4);
  assert("day is 1-based and numeric", flags[0]?.day === 5, JSON.stringify(flags[0]?.day));
  assert("target names the venue", flags[0]?.target === "La Rapiere", flags[0]?.target);
  assert("message states the computed date", /2026-10-05/.test(flags[0]?.message || ""), flags[0]?.message);
  assert("message states the true weekday", /Monday/.test(flags[0]?.message || ""), flags[0]?.message);
  assert("the correction is logged for qc.fixes",
    corrections.length === 1 && /Tuesday/.test(corrections[0]) && /Monday/.test(corrections[0]),
    JSON.stringify(corrections));
  assert("the input plan is not mutated",
    /this is a Tuesday/.test(plan.days[4].items[0].verify_status));
}

console.log("\n=== the phrasings that count as a self-referential claim ===");
{
  const claim = (text) => {
    const { plan, flags } = assertWeekdayClaims(
      { days: [{ day: 1, notes: text, items: [] }] },
      START, // Day 1 = Thursday 2026-10-01
    );
    return { text: plan.days[0].notes, hit: flags.length > 0 };
  };

  assert("'today is Monday' is corrected", claim("Today is Monday, so book ahead.").text.startsWith("Today is Thursday"));
  assert("'this day is a Sunday' is corrected", claim("This day is a Sunday.").text === "This day is a Thursday.");
  assert("'this is a Tuesday' is corrected", claim("Note: this is a Tuesday.").text === "Note: this is a Thursday.");
  assert("'it's a Friday' is corrected", claim("It's a Friday — expect crowds.").text.startsWith("It's a Thursday"));
  assert("'it is Saturday' is corrected", claim("It is Saturday.").text === "It is Thursday.");

  assert("abbreviations are corrected", claim("Today is Mon.").text === "Today is Thu.");
  assert("ALLCAPS case is preserved", claim("TODAY IS MONDAY").text === "TODAY IS THURSDAY", claim("TODAY IS MONDAY").text);
  assert("lowercase is preserved", claim("today is monday").text === "today is thursday", claim("today is monday").text);

  assert("a correct claim raises nothing", !claim("Today is Thursday.").hit);
  assert("a correct abbreviated claim raises nothing", !claim("Today is Thu.").hit);
}

console.log("\n=== headlines may lead with a weekday ===");
{
  const { plan, flags } = assertWeekdayClaims(
    { days: [{ day: 1, headline: "Monday in Bayeux — market day", items: [] }] },
    START,
  );
  assert("a leading weekday in a headline is corrected",
    plan.days[0].headline === "Thursday in Bayeux — market day", plan.days[0].headline);
  assert("the headline correction is flagged", flags.length === 1);

  // Only leading, and only in the headline — a weekday inside a headline is
  // as likely to be a venue fact as a date claim.
  const inline = assertWeekdayClaims(
    { days: [{ day: 1, headline: "Bayeux — the Monday market", items: [] }] },
    START,
  );
  assert("a weekday inside a headline is left alone",
    inline.plan.days[0].headline === "Bayeux — the Monday market", inline.plan.days[0].headline);
  const inNotes = assertWeekdayClaims(
    { days: [{ day: 1, notes: "Monday is market day here.", items: [] }] },
    START,
  );
  assert("a leading weekday in notes is left alone",
    inNotes.plan.days[0].notes === "Monday is market day here.", inNotes.plan.days[0].notes);
}

console.log("\n=== venue facts are never rewritten ===");
{
  // This is the whole reason the matcher is narrow. A missed claim costs one
  // warn-severity annotation. Rewriting "closed Mondays" to "closed Thursdays"
  // silently destroys Places-verified data and sends someone to a shut door.
  const untouched = [
    "Closed Mondays.",
    "Closed on Mondays and Tuesdays.",
    "The market runs Wednesday and Saturday mornings.",
    "Book by Friday for a weekend table.",
    "Sunday roast is the reason to come.",
    "Open Tuesday–Sunday, 12:00–14:30.",
    "Last entry Sunday at 4:30 PM.",
  ];
  for (const text of untouched) {
    const { plan, flags } = assertWeekdayClaims({ days: [{ day: 1, notes: text, items: [] }] }, START);
    assert(`left alone: "${text}"`, plan.days[0].notes === text && flags.length === 0, plan.days[0].notes);
  }
}

console.log("\n=== fields walked ===");
{
  const plan = {
    days: [{
      day: 1,
      headline: "Monday in London",
      notes: "Today is Monday.",
      verify_status: "Checked — this is a Monday.",
      confirmation_notes: "Reconfirmed; it's a Monday.",
      items: [{
        type: "Activity",
        text: "Tower of London",
        notes: "Today is Monday, quieter than the weekend.",
        verify_status: "Open — this is a Monday.",
        flags: ["Arrive early; today is Monday."],
      }],
    }],
  };
  const { plan: fixed, flags } = assertWeekdayClaims(plan, START);
  const d = fixed.days[0];
  const item = d.items[0];

  assert("day headline corrected", /Thursday in London/.test(d.headline), d.headline);
  assert("day notes corrected", /Today is Thursday/.test(d.notes), d.notes);
  assert("day verify_status corrected", /this is a Thursday/.test(d.verify_status), d.verify_status);
  assert("day confirmation_notes corrected", /it's a Thursday/.test(d.confirmation_notes), d.confirmation_notes);
  assert("item notes corrected", /Today is Thursday/.test(item.notes), item.notes);
  assert("item verify_status corrected", /this is a Thursday/.test(item.verify_status), item.verify_status);
  assert("item string flags corrected", /today is Thursday/.test(item.flags[0]), item.flags[0]);
  assert("every correction is flagged", flags.length === 7, String(flags.length));
  assert("all flags are warn", flags.every(f => f.severity === "warn"));
}

console.log("\n=== degenerate input ===");
{
  const plan = { days: [{ day: 1, notes: "Today is Monday.", items: [] }] };
  assert("missing start date → no change",
    assertWeekdayClaims(plan, undefined).plan === plan);
  assert("malformed start date → no change",
    assertWeekdayClaims(plan, "next tuesday").plan === plan);
  assert("null plan is safe", assertWeekdayClaims(null, START).plan === null);
  assert("no days is safe", assertWeekdayClaims({}, START).flags.length === 0);
  assert("null day entries survive",
    Array.isArray(assertWeekdayClaims({ days: [null, { day: 2, items: [] }] }, START).plan.days));
  assert("a clean plan is returned by reference",
    assertWeekdayClaims({ days: [{ day: 1, notes: "Nothing to see.", items: [] }] }, START).flags.length === 0);
}

console.log("\n=== enforceDayLabelDates — day.label's own date stamp (2026-08-09 regression) ===");
{
  // Real observed case, three independent exports of the same
  // London/Normandy/Nuremberg/Porto build: Day 5 labeled "Wed Oct 15" and
  // Day 6 labeled "Thu Oct 15" — the identical date twice, Oct 14 skipped
  // from the sequence entirely. assertWeekdayClaims never caught this
  // because it only scans PROSE fields (headline, notes, ...), never the
  // label's own date segment. Trip starts Sat Oct 10, 2026.
  const LABEL_START = "2026-10-10";
  const brokenLabels = {
    days: [
      { label: "Day 1 · Sat Oct 10 · Arrive London", city: "London", items: [] },
      { label: "Day 2 · Sun Oct 11 · Settle into London", city: "London", items: [] },
      { label: "Day 3 · Mon Oct 12 · Imperial War Museum", city: "London", items: [] },
      { label: "Day 4 · Tue Oct 13 · Bletchley Park day trip", city: "London", items: [] },
      { label: "Day 5 · Wed Oct 15 · Depart for Normandy", city: "Normandy", items: [] },
      { label: "Day 6 · Thu Oct 15 · Normandy D-Day exploration", city: "Normandy", items: [] },
    ],
  };
  const result = enforceDayLabelDates(brokenLabels, LABEL_START);
  assert("Day 5's wrong date stamp is corrected from Oct 15 to Oct 14",
    result.plan.days[4].label === "Day 5 · Wed Oct 14 · Depart for Normandy", result.plan.days[4].label);
  assert("Day 6's already-correct stamp (Thu Oct 15) is left untouched",
    result.plan.days[5].label === "Day 6 · Thu Oct 15 · Normandy D-Day exploration", result.plan.days[5].label);
  assert("the 4 already-correct days are untouched (same object references)",
    [0, 1, 2, 3].every(i => result.plan.days[i] === brokenLabels.days[i]));
  assert("exactly one flag raised, for Day 5 only",
    result.flags.length === 1 && result.flags[0].day === 5, JSON.stringify(result.flags));
  assert("the flag is WEEKDAY_CLAIM_MISMATCH, warn severity, targeting the label",
    result.flags[0].code === "WEEKDAY_CLAIM_MISMATCH" && result.flags[0].severity === "warn" && result.flags[0].target === "label");
  assert("one correction string recorded", result.corrections.length === 1, JSON.stringify(result.corrections));

  const alreadyCorrect = {
    days: [
      { label: "Day 1 · Sat Oct 10 · Arrive London", city: "London", items: [] },
      { label: "Day 2 · Sun Oct 11 · Settle into London", city: "London", items: [] },
    ],
  };
  const clean = enforceDayLabelDates(alreadyCorrect, LABEL_START);
  assert("a fully correct plan is returned by reference, no flags", clean.plan === alreadyCorrect && clean.flags.length === 0);

  const malformedLabel = { days: [{ label: "Arrive London", city: "London", items: [] }] };
  assert("a label with fewer than 3 '·' segments is left untouched (fail safe, not guessed at)",
    enforceDayLabelDates(malformedLabel, LABEL_START).plan.days[0].label === "Arrive London");

  assert("missing start date → no change", enforceDayLabelDates(brokenLabels, undefined).plan === brokenLabels);
  assert("malformed start date → no change", enforceDayLabelDates(brokenLabels, "next tuesday").plan === brokenLabels);
  assert("null plan is safe", enforceDayLabelDates(null, LABEL_START).plan === null);
  assert("no days is safe", enforceDayLabelDates({}, LABEL_START).flags.length === 0);
  assert("null day entries survive",
    Array.isArray(enforceDayLabelDates({ days: [null, { label: "Day 2 · Sun Oct 11 · x", items: [] }] }, LABEL_START).plan.days));
}

console.log("\n=== enforceMetaDateRange — trip summary's own date range (2026-08-31 regression) ===");
{
  // Real observed case: a correct 12-night, 13-day Carvoeiro/Évora/Seville
  // build (Day 1 Fri May 2 through Day 13 Wed May 14, exactly matching the
  // 7+2+3 nights sum) shipped with meta reading "Fri May 2–Thu May 15" —
  // one day past the real last day. Both the web export's <title> and hero
  // banner reuse plan.meta verbatim, so the wrong date reached the page
  // even though every day.label underneath it was already correct.
  const META_START = "2025-05-02"; // a real Friday, matching the observed case
  const days13 = Array.from({ length: 13 }, (_, i) => ({ label: `Day ${i + 1} · placeholder`, items: [] }));

  const broken = {
    meta: "Fri May 2–Thu May 15 · 7+2+3 nights · 2 travelers · Luxury boutique · Relaxed pace",
    days: days13,
  };
  const result = enforceMetaDateRange(broken, META_START);
  assert("end date corrected from Thu May 15 to the real last day, Wed May 14",
    result.plan.meta === "Fri May 2–Wed May 14 · 7+2+3 nights · 2 travelers · Luxury boutique · Relaxed pace",
    result.plan.meta);
  assert("exactly one flag raised, targeting meta",
    result.flags.length === 1 && result.flags[0].target === "meta", JSON.stringify(result.flags));
  assert("the flag is WEEKDAY_CLAIM_MISMATCH, warn severity",
    result.flags[0].code === "WEEKDAY_CLAIM_MISMATCH" && result.flags[0].severity === "warn");
  assert("one correction string recorded", result.corrections.length === 1, JSON.stringify(result.corrections));

  const alreadyCorrect = {
    meta: "Fri May 2–Wed May 14 · 7+2+3 nights · 2 travelers · Luxury boutique · Relaxed pace",
    days: days13,
  };
  const clean = enforceMetaDateRange(alreadyCorrect, META_START);
  assert("an already-correct meta is returned by reference, no flags",
    clean.plan === alreadyCorrect && clean.flags.length === 0);

  const emDash = {
    meta: "Fri May 2—Thu May 15 · 7+2+3 nights",
    days: days13,
  };
  assert("an em dash separator is preserved in the correction",
    enforceMetaDateRange(emDash, META_START).plan.meta === "Fri May 2—Wed May 14 · 7+2+3 nights");

  const unrecognized = { meta: "Our Portugal & Spain trip · 12 nights", days: days13 };
  assert("a meta string with no recognizable date-range clause is left untouched (fail safe)",
    enforceMetaDateRange(unrecognized, META_START).plan === unrecognized);

  assert("missing meta field → no change", enforceMetaDateRange({ days: days13 }, META_START).flags.length === 0);
  assert("missing start date → no change", enforceMetaDateRange(broken, undefined).plan === broken);
  assert("malformed start date → no change", enforceMetaDateRange(broken, "next tuesday").plan === broken);
  assert("null plan is safe", enforceMetaDateRange(null, META_START).plan === null);
  assert("no days is safe", enforceMetaDateRange({ meta: broken.meta, days: [] }, META_START).flags.length === 0);
}

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
