// Tests for assertWeekdayClaims in src/dateFacts.js (report bug 3, validator V3).
//
// Day 5 of the 2026-07-28 build was Monday Oct 5. It booked La Rapiere, which
// closes Mondays, and carried the verify note "this is a Tuesday, confirm
// open". The false premise is what talked the expert review past the closure.
//
// CLAUDE.md: "Day-of-week … COMPUTED IN CODE, never generated by the model."
// So a wrong claim is rewritten, not merely annotated. The rewrite is
// deliberately narrow — see the last block, which is the important one: a
// venue's real closure data must never be edited.

import { assertWeekdayClaims } from "../src/dateFacts.js";

let passed = 0, failed = 0;
function assert(name, cond, detail = "") {
  if (cond) { passed++; console.log("  ✓", name); }
  else { failed++; console.log("  ✗", name, detail); }
}

// 2026-10-01 is a Thursday, so Day 5 is Monday 2026-10-05.
const START = "2026-10-01";

console.log("=== the shipped failure: \"this is a Tuesday\" on a Monday ===");
{
  const plan = {
    days: [
      { day: 1, city: "Bayeux", items: [] },
      { day: 2, city: "Bayeux", items: [] },
      { day: 3, city: "Bayeux", items: [] },
      { day: 4, city: "Bayeux", items: [] },
      {
        day: 5,
        city: "Bayeux",
        items: [{
          type: "Dinner",
          text: "Dinner at La Rapiere",
          restaurant: { name: "La Rapiere" },
          verify_status: "Closed Mondays per Places — but this is a Tuesday, confirm open.",
        }],
      },
    ],
  };
  const { plan: fixed, flags, corrections } = assertWeekdayClaims(plan, START);
  const note = fixed.days[4].items[0].verify_status;

  assert("the self-referential claim is corrected", /this is a Monday/.test(note), note);
  assert("the venue's real closure data is untouched", /Closed Mondays per Places/.test(note), note);
  assert("one flag raised", flags.length === 1, JSON.stringify(flags));
  assert("code is WEEKDAY_CLAIM_MISMATCH", flags[0]?.code === "WEEKDAY_CLAIM_MISMATCH");
  assert("severity is warn — the text is already fixed", flags[0]?.severity === "warn");
  assert("dayIdx is 0-based", flags[0]?.dayIdx === 4);
  assert("day is 1-based and numeric", flags[0]?.day === 5, JSON.stringify(flags[0]?.day));
  assert("target names the venue", flags[0]?.target === "La Rapiere", flags[0]?.target);
  assert("message states the computed date", /2026-10-05/.test(flags[0]?.message || ""), flags[0]?.message);
  assert("message states the true weekday", /Monday/.test(flags[0]?.message || ""), flags[0]?.message);
  assert("the correction is logged for qc.fixes",
    corrections.length === 1 && /Tuesday/.test(corrections[0]) && /Monday/.test(corrections[0]),
    JSON.stringify(corrections));
  assert("the input plan is not mutated",
    /this is a Tuesday/.test(plan.days[4].items[0].verify_status));
}

console.log("\n=== the phrasings that count as a self-referential claim ===");
{
  const claim = (text) => {
    const { plan, flags } = assertWeekdayClaims(
      { days: [{ day: 1, notes: text, items: [] }] },
      START, // Day 1 = Thursday 2026-10-01
    );
    return { text: plan.days[0].notes, hit: flags.length > 0 };
  };

  assert("'today is Monday' is corrected", claim("Today is Monday, so book ahead.").text.startsWith("Today is Thursday"));
  assert("'this day is a Sunday' is corrected", claim("This day is a Sunday.").text === "This day is a Thursday.");
  assert("'this is a Tuesday' is corrected", claim("Note: this is a Tuesday.").text === "Note: this is a Thursday.");
  assert("'it's a Friday' is corrected", claim("It's a Friday — expect crowds.").text.startsWith("It's a Thursday"));
  assert("'it is Saturday' is corrected", claim("It is Saturday.").text === "It is Thursday.");

  assert("abbreviations are corrected", claim("Today is Mon.").text === "Today is Thu.");
  assert("ALLCAPS case is preserved", claim("TODAY IS MONDAY").text === "TODAY IS THURSDAY", claim("TODAY IS MONDAY").text);
  assert("lowercase is preserved", claim("today is monday").text === "today is thursday", claim("today is monday").text);

  assert("a correct claim raises nothing", !claim("Today is Thursday.").hit);
  assert("a correct abbreviated claim raises nothing", !claim("Today is Thu.").hit);
}

console.log("\n=== headlines may lead with a weekday ===");
{
  const { plan, flags } = assertWeekdayClaims(
    { days: [{ day: 1, headline: "Monday in Bayeux — market day", items: [] }] },
    START,
  );
  assert("a leading weekday in a headline is corrected",
    plan.days[0].headline === "Thursday in Bayeux — market day", plan.days[0].headline);
  assert("the headline correction is flagged", flags.length === 1);

  // Only leading, and only in the headline — a weekday inside a headline is
  // as likely to be a venue fact as a date claim.
  const inline = assertWeekdayClaims(
    { days: [{ day: 1, headline: "Bayeux — the Monday market", items: [] }] },
    START,
  );
  assert("a weekday inside a headline is left alone",
    inline.plan.days[0].headline === "Bayeux — the Monday market", inline.plan.days[0].headline);
  const inNotes = assertWeekdayClaims(
    { days: [{ day: 1, notes: "Monday is market day here.", items: [] }] },
    START,
  );
  assert("a leading weekday in notes is left alone",
    inNotes.plan.days[0].notes === "Monday is market day here.", inNotes.plan.days[0].notes);
}

console.log("\n=== venue facts are never rewritten ===");
{
  // This is the whole reason the matcher is narrow. A missed claim costs one
  // warn-severity annotation. Rewriting "closed Mondays" to "closed Thursdays"
  // silently destroys Places-verified data and sends someone to a shut door.
  const untouched = [
    "Closed Mondays.",
    "Closed on Mondays and Tuesdays.",
    "The market runs Wednesday and Saturday mornings.",
    "Book by Friday for a weekend table.",
    "Sunday roast is the reason to come.",
    "Open Tuesday–Sunday, 12:00–14:30.",
    "Last entry Sunday at 4:30 PM.",
  ];
  for (const text of untouched) {
    const { plan, flags } = assertWeekdayClaims({ days: [{ day: 1, notes: text, items: [] }] }, START);
    assert(`left alone: "${text}"`, plan.days[0].notes === text && flags.length === 0, plan.days[0].notes);
  }
}

console.log("\n=== fields walked ===");
{
  const plan = {
    days: [{
      day: 1,
      headline: "Monday in London",
      notes: "Today is Monday.",
      verify_status: "Checked — this is a Monday.",
      confirmation_notes: "Reconfirmed; it's a Monday.",
      items: [{
        type: "Activity",
        text: "Tower of London",
        notes: "Today is Monday, quieter than the weekend.",
        verify_status: "Open — this is a Monday.",
        flags: ["Arrive early; today is Monday."],
      }],
    }],
  };
  const { plan: fixed, flags } = assertWeekdayClaims(plan, START);
  const d = fixed.days[0];
  const item = d.items[0];

  assert("day headline corrected", /Thursday in London/.test(d.headline), d.headline);
  assert("day notes corrected", /Today is Thursday/.test(d.notes), d.notes);
  assert("day verify_status corrected", /this is a Thursday/.test(d.verify_status), d.verify_status);
  assert("day confirmation_notes corrected", /it's a Thursday/.test(d.confirmation_notes), d.confirmation_notes);
  assert("item notes corrected", /Today is Thursday/.test(item.notes), item.notes);
  assert("item verify_status corrected", /this is a Thursday/.test(item.verify_status), item.verify_status);
  assert("item string flags corrected", /today is Thursday/.test(item.flags[0]), item.flags[0]);
  assert("every correction is flagged", flags.length === 7, String(flags.length));
  assert("all flags are warn", flags.every(f => f.severity === "warn"));
}

console.log("\n=== degenerate input ===");
{
  const plan = { days: [{ day: 1, notes: "Today is Monday.", items: [] }] };
  assert("missing start date → no change",
    assertWeekdayClaims(plan, undefined).plan === plan);
  assert("malformed start date → no change",
    assertWeekdayClaims(plan, "next tuesday").plan === plan);
  assert("null plan is safe", assertWeekdayClaims(null, START).plan === null);
  assert("no days is safe", assertWeekdayClaims({}, START).flags.length === 0);
  assert("null day entries survive",
    Array.isArray(assertWeekdayClaims({ days: [null, { day: 2, items: [] }] }, START).plan.days));
  assert("a clean plan is returned by reference",
    assertWeekdayClaims({ days: [{ day: 1, notes: "Nothing to see.", items: [] }] }, START).flags.length === 0);
}

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
