// Pure date / weekday helpers used by buildUserPrompt to inject
// COMPUTED facts into the model context instead of asking the model
// to do its own date math.
//
// The model is empirically unreliable at weekday-of-date calculation
// (Aug 25 2027 was rendered as "Monday" when it's Wednesday; Sep 5
// 2027 came out "Saturday" when it's Sunday). These bugs shipped to a
// user-facing PDF because the only signal was the model's confidence.
//
// Rule from CLAUDE.md: "Day-of-week, durations, time math, and sums
// are COMPUTED IN CODE, never generated by the model."
//
// Anchor dates used in tests:
//   Aug 25 2027 = Wednesday
//   Sep  5 2027 = Sunday
//   Jun  3 2027 = Thursday
//
// CRITICAL: every Date built in this module uses Date.UTC and reads
// via toLocaleDateString(..., { timeZone: 'UTC' }). A naïve
// `new Date('2027-08-25')` would be interpreted as UTC midnight, then
// rendered in the user's local timezone, which in the Americas shifts
// the weekday back by one. The UTC-everywhere approach makes the
// computation timezone-invariant and matches what the user typed.

const WEEKDAY_LONG = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const WEEKDAY_SHORT = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const MONTH_SHORT = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

// Parse "YYYY-MM-DD" into {y,m,d} as integers, or null on bad input.
// We do not accept any other format; the rest of the codebase normalizes
// to ISO date strings at form time.
export function parseISODate(s) {
  if (typeof s !== "string") return null;
  const m = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return null;
  const y = parseInt(m[1], 10);
  const mo = parseInt(m[2], 10);
  const d = parseInt(m[3], 10);
  if (mo < 1 || mo > 12 || d < 1 || d > 31) return null;
  return { y, m: mo, d };
}

// Return the weekday name for an ISO date string. UTC-anchored, so the
// result never shifts by timezone.
//   weekdayOf("2027-08-25") === "Wednesday"
//   weekdayOf("2027-09-05") === "Sunday"
// Returns "" on bad input.
export function weekdayOf(isoDate, opts = {}) {
  const parsed = parseISODate(isoDate);
  if (!parsed) return "";
  const idx = new Date(Date.UTC(parsed.y, parsed.m - 1, parsed.d)).getUTCDay();
  return opts.short ? WEEKDAY_SHORT[idx] : WEEKDAY_LONG[idx];
}

// Add N days to an ISO date string. Returns "" on bad input.
//   addDays("2027-08-25", 1) === "2027-08-26"
//   addDays("2027-08-31", 1) === "2027-09-01"
export function addDays(isoDate, n) {
  const parsed = parseISODate(isoDate);
  if (!parsed) return "";
  const t = Date.UTC(parsed.y, parsed.m - 1, parsed.d) + n * 86_400_000;
  const dt = new Date(t);
  const y = dt.getUTCFullYear();
  const m = String(dt.getUTCMonth() + 1).padStart(2, "0");
  const d = String(dt.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

// Format an ISO date as the short stamp we put in day labels, e.g.
// "Wed Aug 25". Skips year (the trip already states it).
export function shortStamp(isoDate) {
  const parsed = parseISODate(isoDate);
  if (!parsed) return "";
  const idx = new Date(Date.UTC(parsed.y, parsed.m - 1, parsed.d)).getUTCDay();
  return `${WEEKDAY_SHORT[idx]} ${MONTH_SHORT[parsed.m - 1]} ${parsed.d}`;
}

// Build the computed-date table the model gets fed verbatim. Returns a
// string ready to drop into the user prompt. Format:
//
//   COMPUTED DATE TABLE (use these verbatim — do not recompute):
//   Day 1 — Thu Jun 3, 2027
//   Day 2 — Fri Jun 4, 2027
//   ...
//
// `startISO` is the trip start date (the arrival day). `totalDays` is
// the count of day rows the model needs to emit (nights + 1).
export function buildDateTable(startISO, totalDays) {
  const parsed = parseISODate(startISO);
  if (!parsed || !Number.isInteger(totalDays) || totalDays < 1) return "";
  const lines = ["COMPUTED DATE TABLE (use these verbatim — do not recompute, do not guess weekdays):"];
  for (let i = 0; i < totalDays; i++) {
    const iso = addDays(startISO, i);
    const stamp = shortStamp(iso);
    const p = parseISODate(iso);
    lines.push(`Day ${i + 1} — ${stamp}, ${p.y}`);
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Weekday claims in model prose (report bug 3, validator V3)
// ---------------------------------------------------------------------------
//
// Feeding the model a computed date table stops it inventing the day LABEL,
// but it still writes weekdays into free prose. The 2026-07-28 build put a
// Monday-closed restaurant on Monday Oct 5 with a verify note reading "this is
// a Tuesday, confirm open" — the false premise is what let the closure through
// the expert review.
//
// Day-of-week is code's per CLAUDE.md, so we do not merely flag the claim: we
// rewrite it to the computed weekday and record the correction. Case and
// abbreviation are preserved so "Mon" stays "Tue" and "MONDAY" stays "TUESDAY".

// Prose fields the model authors on a day and on its items. Anything the model
// can write a weekday into needs to be scanned; anything code writes does not.
const DAY_PROSE_FIELDS = ["headline", "notes", "verify_status", "confirmation_notes"];
const ITEM_PROSE_FIELDS = ["notes", "verify_status", "confirmation_notes"];

const WD = "(Sun|Mon|Tues?|Wed(?:nes)?|Thur?s?|Fri|Sat(?:ur)?)(day)?";

// Only SELF-REFERENTIAL weekday claims are corrected — prose that asserts what
// day *this day* is. A blanket rewrite would corrupt the legitimate mentions
// that share the same fields: "closed Mondays", "market runs Sat–Sun", "book by
// Friday" are all facts about other days and must survive untouched.
//
// Deliberately narrow. A missed claim stays a warn-severity annotation; a
// wrongly-rewritten closure note silently destroys venue data. The failing
// string from the 2026-07-28 build ("this is a Tuesday, confirm open") is
// covered by the second pattern.
const SELF_REFERENTIAL = [
  new RegExp(`\\b(?:today|this day)\\s+is\\s+(?:an?\\s+)?${WD}\\b`, "gi"),
  new RegExp(`\\bthis\\s+is\\s+(?:an?\\s+)?${WD}\\b`, "gi"),
  new RegExp(`\\bit(?:'s|’s|\\s+is)\\s+(?:an?\\s+)?${WD}\\b`, "gi"),
];

// A day headline that opens with a bare weekday is asserting the day's own
// weekday ("Monday in Bayeux — market morning"). Applied to headline only.
const LEADING_WEEKDAY = new RegExp(`^\\s*${WD}\\b`, "i");

const CANON = {
  sun: 0, sunday: 0,
  mon: 1, monday: 1,
  tue: 2, tues: 2, tuesday: 2,
  wed: 3, wednes: 3, wednesday: 3,
  thu: 4, thur: 4, thurs: 4, thursday: 4,
  fri: 5, friday: 5,
  sat: 6, satur: 6, saturday: 6,
};

// Re-case `replacement` to match the shape of `original`: ALL CAPS stays all
// caps, lowercase stays lowercase, anything else gets Title Case.
function matchCase(original, replacement) {
  if (original === original.toUpperCase()) return replacement.toUpperCase();
  if (original === original.toLowerCase()) return replacement.toLowerCase();
  return replacement;
}

// Rewrite the weekday inside a matched self-referential phrase. `stem`/`suffix`
// are the capture groups from WD; the surrounding phrase is preserved verbatim
// so "this is a Tuesday" becomes "this is a Monday", not "Monday".
function rewriteMatch(match, stem, suffix, correctIdx, claims) {
  const claimedIdx = CANON[stem.toLowerCase()];
  if (claimedIdx === undefined || claimedIdx === correctIdx) return match;
  // Keep the writer's abbreviation style: "Mon" → "Tue", "Monday" → "Tuesday".
  const token = `${stem}${suffix || ""}`;
  const target = suffix ? WEEKDAY_LONG[correctIdx] : WEEKDAY_SHORT[correctIdx];
  const corrected = matchCase(token, target);
  claims.push({ claimed: token, corrected });
  return match.slice(0, match.length - token.length) + corrected;
}

// Correct self-referential weekday claims in `text`. Returns { text, claims };
// claims is empty when the prose said nothing about which day this is, or said
// it correctly.
function correctWeekdaysIn(text, correctIdx, { leading = false } = {}) {
  const claims = [];
  let next = String(text);
  for (const re of SELF_REFERENTIAL) {
    re.lastIndex = 0;
    next = next.replace(re, (match, stem, suffix) => rewriteMatch(match, stem, suffix, correctIdx, claims));
  }
  if (leading) {
    next = next.replace(LEADING_WEEKDAY, (match, stem, suffix) => rewriteMatch(match, stem, suffix, correctIdx, claims));
  }
  return { text: next, claims };
}

// Cross-check every weekday the model wrote in prose against the computed
// calendar, correcting as it goes.
//
// `startDateISO` is the trip's arrival date; day N is startDate + (N-1). Days
// are matched by index, not by parsing the label, because the label is itself
// model-adjacent text this function may be correcting.
//
// Returns { plan, flags, corrections }. `plan` is the input reference when
// nothing changed, so callers can keep memoization cheap.
export function assertWeekdayClaims(plan, startDateISO) {
  const days = Array.isArray(plan?.days) ? plan.days : [];
  if (days.length === 0 || !parseISODate(startDateISO)) {
    return { plan, flags: [], corrections: [] };
  }

  const flags = [];
  const corrections = [];
  let changed = false;

  const nextDays = days.map((day, dayIdx) => {
    const iso = addDays(startDateISO, dayIdx);
    const parsed = parseISODate(iso);
    if (!parsed || !day || typeof day !== "object") return day;
    const correctIdx = new Date(Date.UTC(parsed.y, parsed.m - 1, parsed.d)).getUTCDay();
    const label = day.label || `Day ${dayIdx + 1}`;
    let nextDay = day;

    const record = (target, field, claims) => {
      for (const c of claims) {
        flags.push({
          code: "WEEKDAY_CLAIM_MISMATCH",
          severity: "warn",
          dayIdx,
          day: dayIdx + 1,
          target,
          message: `${target}: "${c.claimed}" is wrong — ${iso} is a ${WEEKDAY_LONG[correctIdx]}. Corrected to "${c.corrected}" in ${field}.`,
        });
        corrections.push(`Day ${dayIdx + 1} ${field}: "${c.claimed}" → "${c.corrected}" (${iso} is a ${WEEKDAY_LONG[correctIdx]})`);
      }
    };

    for (const field of DAY_PROSE_FIELDS) {
      if (typeof day[field] !== "string" || !day[field]) continue;
      const { text, claims } = correctWeekdaysIn(day[field], correctIdx, { leading: field === "headline" });
      if (claims.length === 0) continue;
      nextDay = { ...nextDay, [field]: text };
      record(label, field, claims);
      changed = true;
    }

    const items = Array.isArray(day.items) ? day.items : null;
    if (items) {
      let itemsChanged = false;
      const nextItems = items.map((item) => {
        if (!item || typeof item !== "object") return item;
        let nextItem = item;
        const name = item.restaurant?.name || item.text || item.location || label;
        for (const field of ITEM_PROSE_FIELDS) {
          if (typeof item[field] !== "string" || !item[field]) continue;
          const { text, claims } = correctWeekdaysIn(item[field], correctIdx);
          if (claims.length === 0) continue;
          nextItem = { ...nextItem, [field]: text };
          record(name, `item ${field}`, claims);
          itemsChanged = true;
        }
        if (Array.isArray(item.flags) && item.flags.some((f) => typeof f === "string")) {
          let flagsChanged = false;
          const nextFlags = item.flags.map((f) => {
            if (typeof f !== "string") return f;
            const { text, claims } = correctWeekdaysIn(f, correctIdx);
            if (claims.length === 0) return f;
            record(name, "item flag", claims);
            flagsChanged = true;
            return text;
          });
          if (flagsChanged) { nextItem = { ...nextItem, flags: nextFlags }; itemsChanged = true; }
        }
        return nextItem;
      });
      if (itemsChanged) { nextDay = { ...nextDay, items: nextItems }; changed = true; }
    }

    return nextDay;
  });

  if (!changed) return { plan, flags, corrections };
  return { plan: { ...plan, days: nextDays }, flags, corrections };
}

// ---------------------------------------------------------------------------
// Day label date-stamp enforcement
// ---------------------------------------------------------------------------
//
// assertWeekdayClaims (above) scans free PROSE fields (headline, notes, ...)
// for a weekday CLAIM ("this is a Tuesday") and corrects it against the
// computed calendar. It never touches day.label itself — the field format
// "Day N · <stamp> · <purpose>" (e.g. "Day 1 · Wed Aug 25 · Arrive Santa Fe")
// the model is INSTRUCTED to copy verbatim from the COMPUTED DATE TABLE (see
// buildDateTable) but, per CLAUDE.md's own "computed in code, never
// generated by the model" rule, nothing previously verified it actually did.
//
// Real observed case (2026-08-09, three independent exports of the same
// London/Normandy/Nuremberg/Porto build): Day 5 labeled "Wed Oct 15" and Day
// 6 labeled "Thu Oct 15" — the identical date twice, with Oct 14 skipped
// entirely from the sequence. assertWeekdayClaims never caught this because
// it isn't a weekday CLAIM in prose — it's the label's own date segment,
// wrong independent of whatever prose the model wrote elsewhere that day.
export function enforceDayLabelDates(plan, startDateISO) {
  const days = Array.isArray(plan?.days) ? plan.days : [];
  if (days.length === 0 || !parseISODate(startDateISO)) {
    return { plan, flags: [], corrections: [] };
  }
  const flags = [];
  const corrections = [];
  let changed = false;
  const nextDays = days.map((day, dayIdx) => {
    if (!day || typeof day !== "object" || typeof day.label !== "string") return day;
    const iso = addDays(startDateISO, dayIdx);
    const correctStamp = shortStamp(iso);
    if (!correctStamp) return day;
    // Format contract: "Day N · <stamp> · <purpose>". A label that doesn't
    // split into at least 3 "·"-separated segments is left untouched — fail
    // safe rather than guess at rewriting a shape we don't recognize.
    const parts = day.label.split("·").map((s) => s.trim()).filter((s) => s.length > 0);
    if (parts.length < 3) return day;
    const [dayPart, claimedStamp, ...rest] = parts;
    if (claimedStamp === correctStamp) return day;
    const nextLabel = [dayPart, correctStamp, ...rest].join(" · ");
    flags.push({
      code: "WEEKDAY_CLAIM_MISMATCH",
      severity: "warn",
      dayIdx,
      day: dayIdx + 1,
      target: "label",
      message: `Day ${dayIdx + 1} label: "${claimedStamp}" is wrong — the computed date is "${correctStamp}". Corrected to "${nextLabel}".`,
    });
    corrections.push(`Day ${dayIdx + 1} label: "${claimedStamp}" → "${correctStamp}"`);
    changed = true;
    return { ...day, label: nextLabel };
  });
  if (!changed) return { plan, flags, corrections };
  return { plan: { ...plan, days: nextDays }, flags, corrections };
}
