// Pure date / weekday helpers used by buildUserPrompt to inject
// COMPUTED facts into the model context instead of asking the model
// to do its own date math.
//
// The model is empirically unreliable at weekday-of-date calculation
// (Aug 25 2027 was rendered as "Monday" when it's Wednesday; Sep 5
// 2027 came out "Saturday" when it's Sunday). These bugs shipped to a
// user-facing PDF because the only signal was the model's confidence.
//
// Rule from CLAUDE.md: "Day-of-week, durations, time math, and sums
// are COMPUTED IN CODE, never generated by the model."
//
// Anchor dates used in tests:
//   Aug 25 2027 = Wednesday
//   Sep  5 2027 = Sunday
//   Jun  3 2027 = Thursday
//
// CRITICAL: every Date built in this module uses Date.UTC and reads
// via toLocaleDateString(..., { timeZone: 'UTC' }). A naïve
// `new Date('2027-08-25')` would be interpreted as UTC midnight, then
// rendered in the user's local timezone, which in the Americas shifts
// the weekday back by one. The UTC-everywhere approach makes the
// computation timezone-invariant and matches what the user typed.

const WEEKDAY_LONG = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const WEEKDAY_SHORT = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const MONTH_SHORT = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

// Parse "YYYY-MM-DD" into {y,m,d} as integers, or null on bad input.
// We do not accept any other format; the rest of the codebase normalizes
// to ISO date strings at form time.
export function parseISODate(s) {
  if (typeof s !== "string") return null;
  const m = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return null;
  const y = parseInt(m[1], 10);
  const mo = parseInt(m[2], 10);
  const d = parseInt(m[3], 10);
  if (mo < 1 || mo > 12 || d < 1 || d > 31) return null;
  return { y, m: mo, d };
}

// Return the weekday name for an ISO date string. UTC-anchored, so the
// result never shifts by timezone.
//   weekdayOf("2027-08-25") === "Wednesday"
//   weekdayOf("2027-09-05") === "Sunday"
// Returns "" on bad input.
export function weekdayOf(isoDate, opts = {}) {
  const parsed = parseISODate(isoDate);
  if (!parsed) return "";
  const idx = new Date(Date.UTC(parsed.y, parsed.m - 1, parsed.d)).getUTCDay();
  return opts.short ? WEEKDAY_SHORT[idx] : WEEKDAY_LONG[idx];
}

// Add N days to an ISO date string. Returns "" on bad input.
//   addDays("2027-08-25", 1) === "2027-08-26"
//   addDays("2027-08-31", 1) === "2027-09-01"
export function addDays(isoDate, n) {
  const parsed = parseISODate(isoDate);
  if (!parsed) return "";
  const t = Date.UTC(parsed.y, parsed.m - 1, parsed.d) + n * 86_400_000;
  const dt = new Date(t);
  const y = dt.getUTCFullYear();
  const m = String(dt.getUTCMonth() + 1).padStart(2, "0");
  const d = String(dt.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

// Format an ISO date as the short stamp we put in day labels, e.g.
// "Wed Aug 25". Skips year (the trip already states it).
export function shortStamp(isoDate) {
  const parsed = parseISODate(isoDate);
  if (!parsed) return "";
  const idx = new Date(Date.UTC(parsed.y, parsed.m - 1, parsed.d)).getUTCDay();
  return `${WEEKDAY_SHORT[idx]} ${MONTH_SHORT[parsed.m - 1]} ${parsed.d}`;
}

// Build the computed-date table the model gets fed verbatim. Returns a
// string ready to drop into the user prompt. Format:
//
//   COMPUTED DATE TABLE (use these verbatim — do not recompute):
//   Day 1 — Thu Jun 3, 2027
//   Day 2 — Fri Jun 4, 2027
//   ...
//
// `startISO` is the trip start date (the arrival day). `totalDays` is
// the count of day rows the model needs to emit (nights + 1).
export function buildDateTable(startISO, totalDays) {
  const parsed = parseISODate(startISO);
  if (!parsed || !Number.isInteger(totalDays) || totalDays < 1) return "";
  const lines = ["COMPUTED DATE TABLE (use these verbatim — do not recompute, do not guess weekdays):"];
  for (let i = 0; i < totalDays; i++) {
    const iso = addDays(startISO, i);
    const stamp = shortStamp(iso);
    const p = parseISODate(iso);
    lines.push(`Day ${i + 1} — ${stamp}, ${p.y}`);
  }
  return lines.join("\n");
}
